[|(Library_availabilityPolicy = True);
(Library_valid = (Library_notNull & Library_booksDomain & Library_personsDomain & Library_globalPointsTo & Library_uniqueOwner & Library_availabilityPolicy));
(Library_notNull = ((Library_persons ~= null) & (Library_books ~= null) & (Library_borrows ~= null)));
(Library_booksDomain = ((fieldRead Set_content Library_books) \<subseteq> ((Object_alloc Int Book) \<setminus> {null})));
(Library_personsDomain = ((fieldRead Set_content Library_persons) \<subseteq> ((Object_alloc Int Person) \<setminus> {null})));
(Library_globalPointsTo = (ALL p b. (((p, b) : (fieldRead Relation_content Library_borrows)) --> ((p : (fieldRead Set_content Library_persons)) & (b : (fieldRead Set_content Library_books))))));
(Library_uniqueOwner = (ALL b p1 p2. ((((p1, b) : (fieldRead Relation_content Library_borrows)) & ((p2, b) : (fieldRead Relation_content Library_borrows))) --> (p1 = p2))));
comment ''FreeInv ContentAlloc'' (ALL this. (((this : Object_alloc) & (this : Set)) --> ((fieldRead Set_content this) \<subseteq> Object_alloc)));
comment ''FreeInv '' (ALL this. (((this : Object_alloc) & (this : Relation)) --> (ALL x y. (((x, y) : (fieldRead Relation_content this)) --> ((x : Object_alloc) & (y : Object_alloc)))))); 
comment ''FreeInv '' (ALL this. (((this : Object_alloc) & (this : FuncList)) --> ((fieldRead FuncList_content this) \<subseteq> Object_alloc)));
comment ''FreeInv '' (ALL this. (((this : Object_alloc) & (this : AssocList)) --> ({v. (EX k. ((k, v) : (fieldRead AssocList_content this)))} \<subseteq> Object_alloc)));
comment ''FreeInv '' (ALL this. (((this : Object_alloc) & (this : AssocList)) --> ({k. (EX v. ((k, v) : (fieldRead AssocList_content this)))} \<subseteq> Object_alloc)));
((fieldRead Set_lst null) = null);
((fieldRead Relation_assoc null) = null);
((fieldRead Book_title null) = null);
((fieldRead Book_author null) = null);
((fieldRead Person_firstName null) = null);
((fieldRead Person_lastName null) = null);
((fieldRead FuncList_data null) = null);
((fieldRead FuncList_next null) = null);
((fieldRead AssocList_key null) = null);
((fieldRead AssocList_data null) = null);
((fieldRead AssocList_next null) = null);
(ALL xObj. (xObj : Object));
((FuncList Int AssocList) = {null});
((Person Int AssocList) = {null});
((Person Int FuncList) = {null});
((Book Int AssocList) = {null});
((Book Int FuncList) = {null});
((Book Int Person) = {null});
((Relation Int AssocList) = {null});
((Relation Int FuncList) = {null});
((Relation Int Person) = {null});
((Relation Int Book) = {null});
((Set Int AssocList) = {null});
((Set Int FuncList) = {null});
((Set Int Person) = {null});
((Set Int Book) = {null});
((Set Int Relation) = {null});
((Library Int AssocList) = {null});
((Library Int FuncList) = {null});
((Library Int Person) = {null});
((Library Int Book) = {null});
((Library Int Relation) = {null});
((Library Int Set) = {null});
((String Int AssocList) = {null});
((String Int FuncList) = {null});
((String Int Person) = {null});
((String Int Book) = {null});
((String Int Relation) = {null});
((String Int Set) = {null});
((String Int Library) = {null});
((Array Int AssocList) = {null});
((Array Int FuncList) = {null});
((Array Int Person) = {null});
((Array Int Book) = {null});
((Array Int Relation) = {null});
((Array Int Set) = {null});
((Array Int Library) = {null});
((Array Int String) = {null});
(null : Object_alloc);
(Library_persons : Object_alloc);
(Library_books : Object_alloc);
(Library_borrows : Object_alloc);
(pointsto Set Set_lst FuncList);
(pointsto Person Person_firstName String);
(pointsto Person Person_lastName String);
(pointsto FuncList FuncList_data Object);
(pointsto FuncList FuncList_next FuncList);
(pointsto AssocList AssocList_key Object);
(pointsto AssocList AssocList_data Object);
(pointsto AssocList AssocList_next AssocList);
comment ''unalloc_lonely_Object'' (ALL x. (((x : Object) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_Array'' (ALL x. (((x : Array) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_String'' (ALL x. (((x : String) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_Library'' (ALL x. (((x : Library) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_Set'' (ALL x. (((x : Set) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_Relation'' (ALL x. (((x : Relation) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_Book'' (ALL x. (((x : Book) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_Person'' (ALL x. (((x : Person) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_FuncList'' (ALL x. (((x : FuncList) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
comment ''unalloc_lonely_AssocList'' (ALL x. (((x : AssocList) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Set_lst y) ~= x)) & (ALL y. ((fieldRead Relation_assoc y) ~= x)) & (ALL y. ((fieldRead Book_title y) ~= x)) & (ALL y. ((fieldRead Book_author y) ~= x)) & (ALL y. ((fieldRead Person_firstName y) ~= x)) & (ALL y. ((fieldRead Person_lastName y) ~= x)) & (ALL y. ((fieldRead FuncList_data y) ~= x)) & (ALL y. ((fieldRead FuncList_next y) ~= x)) & (ALL y. ((fieldRead AssocList_key y) ~= x)) & (ALL y. ((fieldRead AssocList_data y) ~= x)) & (ALL y. ((fieldRead AssocList_next y) ~= x)) & ((fieldRead Set_lst x) = null) & ((fieldRead Relation_assoc x) = null) & ((fieldRead Book_title x) = null) & ((fieldRead Book_author x) = null) & ((fieldRead Person_firstName x) = null) & ((fieldRead Person_lastName x) = null) & ((fieldRead FuncList_data x) = null) & ((fieldRead FuncList_next x) = null) & ((fieldRead AssocList_key x) = null) & ((fieldRead AssocList_data x) = null) & ((fieldRead AssocList_next x) = null))));
(Library_persons : Set);
(Library_books : Set);
(Library_borrows : Relation);
comment ''ProcedurePrecondition'' (Library_valid=True);
comment ''ProcedurePrecondition'' (b ~= null);
comment ''ProcedurePrecondition'' (b : (fieldRead Set_content Library_books));
comment ''b_type'' (b : Book);
comment ''b_type'' (b : Object_alloc);
comment ''tmp_1_type'' (tmp_1 : Person);
comment ''tmp_1_type'' (tmp_1 : Object_alloc);
comment ''p_type'' (p : Person);
comment ''p_type'' (p : Object_alloc);
(Library_booksDomain_29 = ((fieldRead Set_content Library_books) \<subseteq> ((Object_alloc_30 Int Book) \<setminus> {null})));
(Library_personsDomain_28 = ((fieldRead Set_content Library_persons) \<subseteq> ((Object_alloc_30 Int Person) \<setminus> {null})));
(Library_valid_27 = (Library_notNull & Library_booksDomain_29 & Library_personsDomain_28 & Library_globalPointsTo & Library_uniqueOwner & Library_availabilityPolicy));
comment ''Library.currentReader_Postcondition'' ((tmp_1_26 = null) --> (ALL p. ((p, b) ~: (fieldRead Relation_content Library_borrows))));
comment ''Library.currentReader_Postcondition'' ((tmp_1_26 ~= null) --> ((tmp_1_26, b) : (fieldRead Relation_content Library_borrows)));
comment ''Library.currentReader_Postcondition'' Library_valid_27;
comment ''Library.currentReader_Postcondition'' (Object_alloc \<subseteq> Object_alloc_30);
comment ''tmp_1_type'' (tmp_1_26 : Person);
comment ''tmp_1_type'' (tmp_1_26 : Object_alloc_30);
(Library_booksDomain_20 = ((fieldRead Set_content_22 Library_books) \<subseteq> ((Object_alloc_21 Int Book) \<setminus> {null})));
(Library_personsDomain_19 = ((fieldRead Set_content_22 Library_persons) \<subseteq> ((Object_alloc_21 Int Person) \<setminus> {null})));
(Library_globalPointsTo_18 = (ALL p b. (((p, b) : (fieldRead Relation_content Library_borrows)) --> ((p : (fieldRead Set_content_22 Library_persons)) & (b : (fieldRead Set_content_22 Library_books))))));
(Library_valid_17 = (Library_notNull & Library_booksDomain_20 & Library_personsDomain_19 & Library_globalPointsTo_18 & Library_uniqueOwner & Library_availabilityPolicy));
comment ''Set.remove_Postcondition'' ((fieldRead Set_content_22 Library_books) = ((fieldRead Set_content Library_books) \<setminus> {b}));
comment ''Set.remove_Postcondition'' (Object_alloc_30 \<subseteq> Object_alloc_21);
comment ''Set.remove_Postcondition'' (ALL framedObj. (((framedObj : Object_alloc_30) & (framedObj : Set) & (framedObj ~= Library_books)) --> ((fieldRead Set_content_22 framedObj) = (fieldRead Set_content framedObj))));
comment ''TrueBranch'' (tmp_1_26 ~= null);
(Library_booksDomain_11 = ((fieldRead Set_content_22 Library_books) \<subseteq> ((Object_alloc_12 Int Book) \<setminus> {null})));
(Library_personsDomain_10 = ((fieldRead Set_content_22 Library_persons) \<subseteq> ((Object_alloc_12 Int Person) \<setminus> {null})));
(Library_globalPointsTo_9 = (ALL p__5 b. (((p__5, b) : (fieldRead Relation_content_13 Library_borrows)) --> ((p__5 : (fieldRead Set_content_22 Library_persons)) & (b : (fieldRead Set_content_22 Library_books))))));
(Library_uniqueOwner_8 = (ALL b p1 p2. ((((p1, b) : (fieldRead Relation_content_13 Library_borrows)) & ((p2, b) : (fieldRead Relation_content_13 Library_borrows))) --> (p1 = p2))));
(Library_valid_7 = (Library_notNull & Library_booksDomain_11 & Library_personsDomain_10 & Library_globalPointsTo_9 & Library_uniqueOwner_8 & Library_availabilityPolicy));
comment ''Relation.remove_Postcondition'' ((fieldRead Relation_content_13 Library_borrows) = ((fieldRead Relation_content Library_borrows) \<setminus> {(tmp_1_26, b)}));
comment ''Relation.remove_Postcondition'' (Object_alloc_21 \<subseteq> Object_alloc_12);
comment ''Relation.remove_Postcondition'' (ALL framedObj. (((framedObj : Object_alloc_21) & (framedObj : Relation) & (framedObj ~= Library_borrows)) --> ((fieldRead Relation_content_13 framedObj) = (fieldRead Relation_content framedObj))));
(Library_valid_7=True)|] ==>
    comment ''ProcedureEndPostcondition'' (Library_valid_7 = Library_valid)