([|(List_content = (% this. (fieldRead Node_con (fieldRead List_first this))));
(List_edge = (% x y. (((x : Node) & (y = (fieldRead Node_next x))) | ((x : List) & (y = (fieldRead List_first x))))));
((fieldRead Node_data null) = null);
((fieldRead Node_next null) = null);
((fieldRead List_first null) = null);
(ALL xObj. (xObj : Object));
((Node Int List) = {null});
((Array Int List) = {null});
((Array Int Node) = {null});
(null : Object_alloc);
(pointsto Node Node_data Object);
(pointsto Node Node_next Node);
(pointsto List List_first Node);
comment ''unalloc_lonely_Object'' (ALL x. (((x : Object) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Node_data y) ~= x)) & (ALL y. ((fieldRead Node_next y) ~= x)) & (ALL y. ((fieldRead List_first y) ~= x)) & ((fieldRead Node_data x) = null) & ((fieldRead Node_next x) = null) & ((fieldRead List_first x) = null))));
comment ''unalloc_lonely_Array'' (ALL x. (((x : Array) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Node_data y) ~= x)) & (ALL y. ((fieldRead Node_next y) ~= x)) & (ALL y. ((fieldRead List_first y) ~= x)) & ((fieldRead Node_data x) = null) & ((fieldRead Node_next x) = null) & ((fieldRead List_first x) = null))));
comment ''unalloc_lonely_Node'' (ALL x. (((x : Node) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Node_data y) ~= x)) & (ALL y. ((fieldRead Node_next y) ~= x)) & (ALL y. ((fieldRead List_first y) ~= x)) & ((fieldRead Node_data x) = null) & ((fieldRead Node_next x) = null) & ((fieldRead List_first x) = null))));
comment ''unalloc_lonely_List'' (ALL x. (((x : List) & (x ~: Object_alloc)) --> ((ALL y. ((fieldRead Node_data y) ~= x)) & (ALL y. ((fieldRead Node_next y) ~= x)) & (ALL y. ((fieldRead List_first y) ~= x)) & ((fieldRead Node_data x) = null) & ((fieldRead Node_next x) = null) & ((fieldRead List_first x) = null))));
comment ''List_PrivateInv InjProcedurePrecondition'' (ALL x1 x2 y. (((y ~= null) & (List_edge x1 y) & (List_edge x2 y)) --> (x1 = x2)));
comment ''WhileIn_List_OutsidePublicInvOf_Node ConNullProcedurePrecondition'' (ALL this__25. (((this__25 : Object_alloc) & (this__25 : Node) & (this__25 = null)) --> ((fieldRead Node_con this__25) = {})));
comment ''WhileIn_List_OutsidePublicInvOf_Node ConDefProcedurePrecondition'' (ALL this__26. (((this__26 : Object_alloc) & (this__26 : Node) & (this__26 ~= null)) --> (((fieldRead Node_con this__26) = ({(fieldRead Node_data this__26)} Un (fieldRead Node_con (fieldRead Node_next this__26)))) & ((fieldRead Node_data this__26) ~: (fieldRead Node_con (fieldRead Node_next this__26))))));
comment ''thisNotNull'' (this ~= null);
comment ''thisType'' (this : List);
comment ''thisType'' (this : Object_alloc);
comment ''o1_type'' (o1 : Object);
comment ''o1_type'' (o1 : Object_alloc);
comment ''tmp_12_type'' (tmp_12 : Node);
comment ''tmp_12_type'' (tmp_12 : Object_alloc);
comment ''nxt_type'' (nxt : Node);
comment ''nxt_type'' (nxt : Object_alloc);
comment ''tmp_11_type'' (tmp_11 : Node);
comment ''tmp_11_type'' (tmp_11 : Object_alloc);
comment ''tmp_9_type'' (tmp_9 : Object);
comment ''tmp_9_type'' (tmp_9 : Object_alloc);
comment ''tmp_8_type'' (tmp_8 : Node);
comment ''tmp_8_type'' (tmp_8 : Object_alloc);
comment ''current_type'' (current : Node);
comment ''current_type'' (current : Object_alloc);
comment ''tmp_7_type'' (tmp_7 : Node);
comment ''tmp_7_type'' (tmp_7 : Object_alloc);
comment ''prev_type'' (prev : Node);
comment ''prev_type'' (prev : Object_alloc);
comment ''tmp_5_type'' (tmp_5 : Node);
comment ''tmp_5_type'' (tmp_5 : Object_alloc);
comment ''second_type'' (second : Node);
comment ''second_type'' (second : Object_alloc);
comment ''tmp_3_type'' (tmp_3 : Object);
comment ''tmp_3_type'' (tmp_3 : Object_alloc);
comment ''tmp_2_type'' (tmp_2 : Node);
comment ''tmp_2_type'' (tmp_2 : Object_alloc);
comment ''f_type'' (f : Node);
comment ''f_type'' (f : Object_alloc);
comment ''List.member_Postcondition'' (tmp_1_50 = (o1 : (fieldRead List_content this)));
comment ''List.member_Postcondition'' (Object_alloc \<subseteq> Object_alloc_51);
comment ''List_PrivateInv InjList.member_Postcondition'' (ALL x1 x2 y. (((y ~= null) & (List_edge x1 y) & (List_edge x2 y)) --> (x1 = x2)));
comment ''WhileIn_List_OutsidePublicInvOf_Node ConNullList.member_Postcondition'' (ALL this__29. (((this__29 : Object_alloc_51) & (this__29 : Node) & (this__29 = null)) --> ((fieldRead Node_con this__29) = {})));
comment ''WhileIn_List_OutsidePublicInvOf_Node ConDefList.member_Postcondition'' (ALL this__30. (((this__30 : Object_alloc_51) & (this__30 : Node) & (this__30 ~= null)) --> (((fieldRead Node_con this__30) = ({(fieldRead Node_data this__30)} Un (fieldRead Node_con (fieldRead Node_next this__30)))) & ((fieldRead Node_data this__30) ~: (fieldRead Node_con (fieldRead Node_next this__30))))));
comment ''TrueBranch'' tmp_1_50;
((fieldRead List_first this) ~= null);
comment ''wonder1'' ((fieldRead Node_con (fieldRead Node_next (fieldRead List_first this))) = ((fieldRead Node_con (fieldRead List_first this)) \<setminus> {(fieldRead Node_data (fieldRead List_first this))}));
comment ''FalseBranch'' ((fieldRead Node_data (fieldRead List_first this)) ~= o1);
(List_content_42 = (% this__11. (fieldRead (fieldWrite Node_con (fieldRead List_first this) ((fieldRead Node_con (fieldRead List_first this)) \<setminus> {o1})) (fieldRead List_first this__11))));
(List_content_33 = (% this__12. (fieldRead Node_con_39 (fieldRead List_first this__12))));
comment ''AssumingLoopInv'' (prev_38 : Node);
comment ''AssumingLoopInv'' (prev_38 : Object_alloc_51);
comment ''AssumingLoopInv'' (prev_38 ~= null);
comment ''AssumingLoopInv'' ((fieldRead Node_con_39 prev_38) = ((fieldRead Node_con prev_38) \<setminus> {o1}));
comment ''AssumingLoopInv'' (current_36 : Node);
comment ''AssumingLoopInv'' (current_36 : Object_alloc_51);
comment ''AssumingLoopInv'' (current_36 ~= null);
comment ''AssumingLoopInv'' ((fieldRead Node_next prev_38) = current_36);
comment ''AssumingLoopInv'' (prev_38 ~= current_36);
comment ''AssumingLoopInv'' ((fieldRead List_content_33 this) = ((fieldRead List_content this) \<setminus> {o1}));
comment ''AssumingLoopInv'' (ALL n. (((n : List) & (n : Object_alloc) & (n ~= this)) --> ((fieldRead List_content_33 n) = (fieldRead List_content n))));
comment ''AssumingLoopInv'' (o1 : (fieldRead Node_con_39 current_36));
comment ''ConDefInvAssumingLoopInv'' (ALL n. (((n : Node) & (n : Object_alloc_51) & (n ~= null) & (n ~= prev_38)) --> (((fieldRead Node_con_39 n) = ({(fieldRead Node_data n)} Un (fieldRead Node_con_39 (fieldRead Node_next n)))) & ((fieldRead Node_data n) ~: (fieldRead Node_con_39 (fieldRead Node_next n))))));
comment ''AssumingLoopInv'' (ALL n. (((fieldRead Node_con_39 n) = (fieldRead Node_con n)) | ((fieldRead Node_con_39 n) = ((fieldRead Node_con n) \<setminus> {o1}))));
comment ''AssumingLoopInv'' ((fieldRead Node_con_39 null) = {});
comment ''LoopConditionFalse'' (~((fieldRead Node_data current_36) ~= o1));
comment ''FalseBranch'' ((fieldRead Node_next current_36) ~= null);
(List_edge_21 = (% x y. (((x : Node) & (y = (fieldRead (fieldWrite Node_next prev_38 (fieldRead Node_next current_36)) x))) | ((x : List) & (y = (fieldRead List_first x))))));
(List_edge_19 = (% x y. (((x : Node) & (y = (fieldRead (fieldWrite (fieldWrite Node_next prev_38 (fieldRead Node_next current_36)) current_36 null) x))) | ((x : List) & (y = (fieldRead List_first x))))));
(List_content_17 = (% this__21. (fieldRead (fieldWrite Node_con_39 current_36 {(fieldRead Node_data current_36)}) (fieldRead List_first this__21))));
(y ~= null);
(List_edge_19 x1 y);
(List_edge_19 x2 y)|] ==>
    comment ''List_PrivateInv Inj_ProcedureEndPostcondition'' (x1 = x2))