theory loadTree_Node_lemmas = Jahob:

lemma Node_loadTree_18: "([|comment ''NewThisChildren'' ((fieldRead (fieldWrite (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_36})) this) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) tmp_6_36) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) this) Node_si tmp_6_36) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) this) i)) & (c ~= null)))});
comment ''MChildren'' ((fieldRead (fieldWrite (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_36})) tmp_6_36) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) tmp_6_36) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) this) Node_si tmp_6_36) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) tmp_6_36) i)) & (c ~= null)))});
comment ''OtherChildren'' (ALL x. (((x ~= this) & (x ~= tmp_6_36) & (x : ((Object_alloc Un {tmp_6_36}) Un {tmp_7_33})) & (x : Node) & (~(fieldRead (fieldWrite Node_isBody tmp_6_36 False) x))) --> ((fieldRead (fieldWrite (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_36})) x) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) tmp_6_36) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) this) Node_si tmp_6_36) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) x) i)) & (c ~= null)))})));
comment ''ChildrenDefRCInv_ChildrenLemma'' (this__12_bv4191 : ((Object_alloc Un {tmp_6_36}) Un {tmp_7_33}));
comment ''ChildrenDefRCInv_ChildrenLemma'' (this__12_bv4191 : Node);
comment ''ChildrenDefRCInv_ChildrenLemma'' (~(fieldRead (fieldWrite Node_isBody tmp_6_36 False) this__12_bv4191))|] ==>
    comment ''ChildrenDefRCInv_ChildrenLemma'' ((fieldRead (fieldWrite (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite (fieldWrite Node_children tmp_6_36 {}) tmp_6_36 ((fieldRead (fieldWrite Node_children tmp_6_36 {}) tmp_6_36) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_36})) this__12_bv4191) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) tmp_6_36) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) this) Node_si tmp_6_36) (fieldRead (fieldWrite Node_subp tmp_6_36 tmp_7_33) this__12_bv4191) i)) & (c ~= null)))}))"
apply (unfold comment_def)
apply (case_tac "this__12_bv4191 = this", simp)
apply (case_tac "this__12_bv4191 = tmp_6_36", simp)
apply (erule_tac x="this__12_bv4191" in allE, simp)
done

end
