theory loadTree_Node_lemmas = Jahob:

lemma Node_loadTree_12: "([|comment ''NewThisChildren'' ((fieldRead (fieldWrite (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_55})) this) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead Node_subp_60 tmp_6_55) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead Node_subp_60 this) Node_si tmp_6_55) (fieldRead Node_subp_60 this) i)) & (c ~= null)))});
comment ''MChildren'' ((fieldRead (fieldWrite (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_55})) tmp_6_55) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead Node_subp_60 tmp_6_55) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead Node_subp_60 this) Node_si tmp_6_55) (fieldRead Node_subp_60 tmp_6_55) i)) & (c ~= null)))});
comment ''OtherChildren'' (ALL x. (((x ~= this) & (x ~= tmp_6_55) & (x : Object_alloc_58) & (x : Node) & (~(fieldRead Node_isBody_59 x))) --> ((fieldRead (fieldWrite (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_55})) x) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead Node_subp_60 tmp_6_55) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead Node_subp_60 this) Node_si tmp_6_55) (fieldRead Node_subp_60 x) i)) & (c ~= null)))})));
comment ''ChildrenDefRCInv_ChildrenLemma'' (this__10_bv4578 : Object_alloc_58);
comment ''ChildrenDefRCInv_ChildrenLemma'' (this__10_bv4578 : Node);
comment ''ChildrenDefRCInv_ChildrenLemma'' (~(fieldRead Node_isBody_59 this__10_bv4578))|] ==>
    comment ''ChildrenDefRCInv_ChildrenLemma'' ((fieldRead (fieldWrite (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this (((fieldRead (fieldWrite Node_children_64 tmp_6_55 ((fieldRead Node_children_64 tmp_6_55) Un {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)})) this) \<setminus> {(arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)}) Un {tmp_6_55})) this__10_bv4578) = {c. (EX i. ((0 <= i) & (intless i 8) & (c = (arrayRead (arrayWrite (arrayWrite Array_arrayState (fieldRead Node_subp_60 tmp_6_55) Node_sj (arrayRead Array_arrayState (fieldRead Node_subp this) Node_si)) (fieldRead Node_subp_60 this) Node_si tmp_6_55) (fieldRead Node_subp_60 this__10_bv4578) i)) & (c ~= null)))}))"
apply (unfold comment_def)
apply (case_tac "this__10_bv4578 = this", simp)
apply (case_tac "this__10_bv4578 = tmp_6_55", simp)
apply (erule_tac x="this__10_bv4578" in allE, simp)
done

end
